wired_xml: cyclonedds_wired.xml
wifi_xml: cyclonedds_wifi.xml
source_domain_id: 15
target_domain_id: 0

topics:
  /tf:
    type: tf2_msgs/msg/TFMessage
    reliable: true        # ← 추가
  /tf_static:
    type: tf2_msgs/msg/TFMessage
    latched: true
    reliable: true        # ← 추가
